modeminfo-qmi: check qmicli utility

diff --git a/root/usr/share/modeminfo/scripts/modeminfo-qmi b/root/usr/share/modeminfo/scripts/modeminfo-qmi
--- a/root/usr/share/modeminfo/scripts/modeminfo-qmi
+++ b/root/usr/share/modeminfo/scripts/modeminfo-qmi
@@ -1,10 +1,15 @@
 # qmi addon for luci-app-modeminfo
-# (c) 2020-2021 written by Konstantine Shevlakov (c) at <shevlakov@132lan.ru>
+# (c) 2020-2022 written by Konstantine Shevlakov (c) at <shevlakov@132lan.ru>
 
 get_device_info(){
 	DEVPORT=$(uci -q get modeminfo.@modeminfo[0].device_qmi)
 	if [ $DEVPORT ]; then
-		export QMICTL="qmicli -p -d $DEVPORT"
+		if [ -x /usr/bin/qmicli ]; then
+			export QMICTL="qmicli -p -d $DEVPORT"
+		else
+			logger -t "luci-app-modeminfo" "qmicli not found!"
+			exit 1
+		fi
 	else
 	       	for qmi in $(ls /dev/cdc-wdm*); do
                 	if [ $qmi ]; then
